### ISSUE TITLE
Add instructions for building tutorial package

### ISSUE THREAD

**Issue by tobi-v** [PilzDE/pilz_tutorials#10]
**Is your feature request related to a problem? Please describe.**
In the [first tutorial](http://wiki.ros.org/pilz_robots/Tutorials/ModelYourApplicationWithPRBT), you start the launch-file in step 8 without building the package or sourcing the setup.bash. This could confuse users who are new to ROS.

**Describe the solution you'd like**
Add a step which describes building the package and sourcing the setup.bash

**Describe alternatives you've considered**
Mention that the package needs to be built as you *always do* and add a reference to the respective ROS tutorial.

**Comment by jschleicher** [comment]
I'd prefer your third option. Step 4 instructs the user to create a package. The link in that section leads to detailed instructions for building and sourcing it. I'd go for a note [there](http://wiki.ros.org/pilz_robots/Tutorials/ModelYourApplicationWithPRBT#Create_your_application_ROS_package)

**Comment by tobi-v** [comment]
In order to not disturb the tutorial's flow, I would rather mention it with a link at the ending of step 7 or the beginning of step 8. Thus we could rule out a potential obstacle and point of frustration.

**Comment by jschleicher** [comment]
Having another look, this is already done within ["Prerequisites"](http://wiki.ros.org/pilz_robots/Tutorials/ModelYourApplicationWithPRBT#Prerequisites). The last bullet point links to "create a catkin workspace" explaining to build and source a workspace. When following this step closely, there is no need for further instructions.

Since there haven't been any complaints by new users so far, I'm suggesting to close here without action. What do you think?
